# This workflow will update the movie list

name: Update Movie List

on:
  workflow_dispatch:

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: checkout repo content
      uses: actions/checkout@v2 # checkout the repository content to github runner
   
    - name: Set up Python 3.9
      uses: actions/setup-python@v2 # install the python version needed
      with:
        python-version: 3.9
        
    - name: Install dependencies  # install the dependencies needed
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt  
        
    - name: execute py script
      run: |
        python rarbg-top10.py
